server:
  port: 8080
  context-path: /sample-service
  tomcat:
    uri-encoding: UTF-8
spring:
  redis:
#    database: 
    host: 127.0.0.1
    port: 6379
    password: 
    pool:
      max-idle: 10
      max-active: 30
      max-wait: 1000
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: abc@123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 10
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  type-aliases-package: org.sample.model
  config-location: classpath:mybatis-config.xml
  mapper-locations:
  - classpath*:/mapper/*.xml