spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: abc@123
    name: test
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: select 'x'
      minimum-idle: 1
      maximum-pool-size: 10
      idle-timeout: 60000
  redis:
#    database:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-idle: 10
      max-active: 30
      max-wait: 1000

server:
  port: 8080
  context-path: /sample-service
  tomcat:
    uri-encoding: UTF-8

mybatis:
  type-aliases-package: org.sample.seckill.model
  config-location: classpath:mybatis-config.xml
  mapper-locations:
  - classpath:/mapper/*.xml